# Generated by Django 5.0.4 on 2024-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
