# Generated by Django 5.0.4 on 2024-04-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_remove_meetup_date_remove_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
